controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Birthday;
use app\models\Birthdays;
use app\models\Categories;
use app\models\forms\Login;
use app\models\People;
use app\models\PeopleCatSearch;
use app\models\PeopleSearch;
use app\models\SubCategory;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\forms\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->layout = 'home';
        Yii::$app->session['activeMenu'] = 'home';
        $categories = Categories::find()->all();
        $counts = [];
        foreach ($categories as $item) {
            $counts[] = [
                'count' => People::find()
                    ->joinWith('category')
                    ->where(['sub_category.category_id' => $item->id])
                    ->count(),
                'title' => $item->title,
                'id' => $item->id
            ];
        }
        $people = People::find()
            ->orderBy(['id' => SORT_DESC])
            ->limit(15)
            ->all();
        $bcount = People::find()
            ->where('month(FROM_UNIXTIME(date)) = month(current_date) and dayofmonth(FROM_UNIXTIME(date)) > dayofmonth(current_date) and dayofmonth(FROM_UNIXTIME(date)) < (dayofmonth(current_date) + 2)')
            ->count();

        return $this->render('index',[
            'counts' => $counts,
            'people' => $people,
            'bcount' => $bcount
        ]);
    }

    public function actionCategory($id)
    {
        $subCat = Categories::findOne($id);
        $searchModel = new PeopleCatSearch();
        Yii::$app->session['activeMenu'] = '99';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $id);

        return $this->render('page', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'subCat' => $subCat
        ]);
    }

    public function actionPage($id)
    {
        $subCat = SubCategory::findOne($id);
        Yii::$app->session['activeMenu'] = $subCat->category_id;
        $searchModel = new PeopleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $id);

        return $this->render('page', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'subCat' => $subCat
        ]);
    }
    public function actionBirthdays()
    {
        $subCat = new SubCategory();
        $subCat->title = Yii::t('app','Охирги 10 кун ичида Тугилган кунлар');
        Yii::$app->session['activeMenu'] = 'birthday';
        $searchModel = new Birthdays();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $searchModel2 = new Birthday();
        $dataProvider2 = $searchModel2->search(Yii::$app->request->queryParams);

        return $this->render('birthdays', [
            'searchModel' => $searchModel,
            'searchModel2' => $searchModel2,
            'dataProvider' => $dataProvider,
            'dataProvider2' => $dataProvider2,
            'subCat' => $subCat
        ]);
    }

    public function actionOpenImg($id)
    {
        $person = People::findOne($id);
        return $this->renderAjax('img-modal',['person' => $person]);
    }

    /**
     * Login
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $model = new Login();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->getUser()->logout();

        return $this->goHome();
    }


}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/birthdays.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->title = $subCat->title;
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">assignment</i>
                    </div>
                    <h4 class="card-title">Охирги 1 кун ичида Тугилган кунлар</h4>
                </div>
                <div class="card-body">
                    <div class="toolbar">
                        <!--        Here you can write extra buttons/actions for the toolbar              -->
                    </div>
                    <div class="material-datatables">
                        <div id="datatables_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <?= GridView::widget([
                                'dataProvider' => $dataProvider2,
                                'filterModel' => $searchModel2,
                                'columns' => [
                                    ['class' => 'yii\grid\SerialColumn'],
                                    'fullname',
                                    'position',
                                    'int_num',
                                    'ip_num',
                                    'home_num',
                                    'phone',
                                    'date:date',
                                    [
                                        'attribute' => 'image',
                                        'value' => function ($model) {
                                            return '<button class="btn btn-info open-img" data-id="'. $model->id.'">Куриш</button>';
                                        },
                                        'format' => 'raw'
                                    ],
                                    //'created_at',
                                    //'updated_at',
                                ],
                            ]); ?>
                        </div>
                    </div>
                    <div class="toolbar">
                        <h4 class="card-title"><?= $subCat->title ?></h4>
                        <!--        Here you can write extra buttons/actions for the toolbar              -->
                    </div>
                    <div class="material-datatables">
                        <div id="datatables_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                'columns' => [
                                    ['class' => 'yii\grid\SerialColumn'],
                                    'fullname',
                                    'position',
                                    'int_num',
                                    'ip_num',
                                    'home_num',
                                    'phone',
                                    'date:date',
                                    [
                                        'attribute' => 'image',
                                        'value' => function ($model) {
                                            return '<button class="btn btn-info open-img" data-id="'. $model->id.'">Куриш</button>';
                                        },
                                        'format' => 'raw'
                                    ],
                                    //'created_at',
                                    //'updated_at',
                                ],
                            ]); ?>
                        </div>
                    </div>
                </div>
                <!-- end content-->
            </div>
            <!--  end card  -->
        </div>
    </div>
</div>

<div class="modal fade" id="noticeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-notice">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">close</i>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-danger btn-round" data-dismiss="modal">Беркитиш</button>
            </div>
        </div>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/img-modal.php
<?php
?>

<div style="text-align: center">
    <div class="row center">
        <div class="col">
            <div class="picture card-avatar">
                <img src="/uploads/<?= $person->image ?>" alt="Thumbnail Image" class="rounded img-fluid" style="max-width: 300px">
            </div>
        </div>
    </div>
    <h4 style="margin-top: 10px"><?= $person->fullname ?></h4>
    <p style="margin-top: 10px"><?= date('d.m.Y',$person->date)?></p>
</div>

views/site/index.php
<div class="container-fluid">
    <div class="row">
        <?php foreach ($counts as $k => $item):?>
        <div class="col">
            <div class="card card-stats">
                <div class="card-header <?=  $k%2===0 ? 'card-header-warning' : 'card-header-info' ?> card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">person</i>
                    </div>
                    <h3 class="card-title"><?= $item['count'] ?>
                        <small>та</small>
                    </h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons text-danger">list</i>
                        <a href="<?= \yii\helpers\Url::to(['/site/category','id' => $item['id']]) ?>"><?= $item['title'] ?></a>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach;?>
        <div class="col">
            <div class="card card-stats">
                <div class="card-header card-header-info card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">notifications</i>
                    </div>
                    <h3 class="card-title"><?= $bcount ?>
                        <small>та</small>
                    </h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons text-danger">list</i>
                        <a href="<?= \yii\helpers\Url::to(['/site/birthdays']) ?>">Тугилган кунлар</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-info">
                    <h4 class="card-title">Сунги кушилганлар</h4>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-warning">
                        <tr>
                            <th>#</th>
                            <th>Исми</th>
                            <th>Лавозими</th>
                            <th>Ички номер</th>
                            <th>4 талик номер</th>
                            <th>Хизмат номери</th>
                            <th>Мобил номери</th>
                            <th>Тугилган куни</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($people as $item):?>
                            <tr>
                                <td>
                                    <div class="round-img">
                                        <a href=""><img src="/uploads/<?=$item->image ?>" alt="" style="max-width: 50px"></a>
                                    </div>
                                </td>
                                <td><?= $item->fullname ?></td>
                                <td><?= $item->position ?></td>
                                <td><?= $item->int_num ?></td>
                                <td><?= $item->ip_num ?></td>
                                <td><?= $item->home_num ?></td>
                                <td><?= $item->phone ?></td>
                                <td><?= date('d.m.Y',$item->date) ?></td>
                            </tr>
                        <?php endforeach;?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/page.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

$this->title = $subCat->title;
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">assignment</i>
                    </div>
                    <h4 class="card-title"><?= $subCat->title ?></h4>
                </div>
                <div class="card-body">
                    <div class="toolbar">
                        <!--        Here you can write extra buttons/actions for the toolbar              -->
                    </div>
                    <div class="material-datatables">
                        <div id="datatables_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                'columns' => [
                                    ['class' => 'yii\grid\SerialColumn'],
                                    'fullname',
                                    'position',
                                    'int_num',
                                    'ip_num',
                                    'home_num',
                                    'phone',
                                    'date:date',
                                    [
                                        'attribute' => 'image',
                                        'value' => function ($model) {
                                            return '<button class="btn btn-info open-img" data-id="'. $model->id.'">Куриш</button>';
                                        },
                                        'format' => 'raw'
                                    ],
                                    //'created_at',
                                    //'updated_at',
                                ],
                            ]); ?>
                        </div>
                    </div>
                </div>
                <!-- end content-->
            </div>
            <!--  end card  -->
        </div>
    </div>
</div>

<div class="modal fade" id="noticeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-notice">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">close</i>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-danger btn-round" data-dismiss="modal">Беркитиш</button>
            </div>
        </div>
    </div>
</div>